version: '3.8'

services:
  app:
    build: .
    container_name: payloadsender
    ports:
      - "5001:5001"
    volumes:
      - ./payloads:/payloads
      - ./config:/config
    restart: unless-stopped
